name: CI pipeline

on:
  release:
    types: [published]
  push:
    branches:
      - '**'

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker.yaml
    with:
      oci_tag: ghcr.io/USER-NAME/git-tutorial
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}
